<div class="page-header clearfix">
    <h2><?php echo !empty($this->customer->getId()) ? 'Edit' : 'New' ?> Customer</h2>
</div>

<form action="" role="form" method="post">
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" name="name"
               id="name" placeholder="Enter Name" value="<?= $this->customer->getName() ?>">
        <?= $this->validationErrors('name') ?>
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" class="form-control" name="email"
               id="email" placeholder="Enter Email" value="<?= $this->customer->getEmail() ?>">
        <?= $this->validationErrors('email') ?>
    </div>
    <button class="btn btn-primary" type="submit">Save</button>
</form>