<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s role="alert">
        <button class="button" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    <div>')
    ->setMessageSeparatorString('</div><div>')
    ->setMessageCloseString('</div></div>');
?>

<?= $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']) ?>
